### ISSUE TITLE
Что это?

### ISSUE THREAD

**Issue by coursar** [Dinar-92/Avito#3]
https://github.com/Dinar-92/Avito/blob/99ccac98d4e8d7f248ee491e4b851f9df082eab3/src/tech/itpark/manager/FlatManager.java#L75-L104

**Comment by Dinar-92** [comment]
Исправлено
https://github.com/Dinar-92/Avito/blob/2f9ddc95b5d2c40922204a8c0b024a3638880f35/src/tech/itpark/manager/FlatManager.java#L70-L72
